### ISSUE TITLE
Could you please bump the new 1.10 version?

### ISSUE THREAD

**Issue by slaw-ik** [keithrbennett/rika#11]
# Gemfile

gem 'rika', '~> 1.10.0', :git => 'https://github.com/ricn/rika.git'

$ bundle update rika
Could not find gem 'rika (~> 1.10.0) ruby' in https://github.com/ricn/rika.git

**Comment by keithrbennett** [comment]
The gem will only be installed when running JRuby. MRI and other Ruby implementations are not supported because Rika relies on the Apache Tika library and its dependencies, which are Java `.jar` files:

```
% ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]

% gem info --remote rika

*** REMOTE GEMS ***

rika (1.6.0)
    Platform: java  # <<<-------------------------------------------------
    Author: Richard Nyström
    Homepage: https://github.com/ricn/rika

    A JRuby wrapper for Apache Tika to extract text and metadata from
    various file formats.

% gem install rika
ERROR:  Could not find a valid gem 'rika' (>= 0) in any repository
ERROR:  Possible alternatives: rtika, ika, mika, pika, rik
```

Changing to JRuby, the `gem install rika` succeeds.

**Comment by keithrbennett** [comment]
As this issue is ancient and there is a new release superseding the one mentioned it, I am closing this issue.
