### ISSUE TITLE
Update Tika dependencies

### ISSUE THREAD

**Issue by keithrbennett** [keithrbennett/rika#13]
The Tika libraries included in this gem are several years old now. Could we update them? I may be able to do this in a PR.

**Comment by ricn** [comment]
I thinks it's a good idea to transfer the ownership of this repository to you so you can continue to maintain it. However, when I tried to transfer it to you I got an error message because you already have a fork called keithrbennett/rika. Can you delete it first so I can transfer it?

**Comment by keithrbennett** [comment]
I have updated the included jar files to include only the single tika-app-1.24.1.jar file in the new release, v 1.11.1. See the [Release Notes](https://github.com/keithrbennett/rika/blob/v1.11.1/RELEASE_NOTES.md) for more information about the release.
